spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/develop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&userSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

