
#sqlite数据库
spring:
  datasource:
    url: jdbc:sqlite:E:\Github\note-admin\note.sqlite # 创建的sqlite数据库所在路径
    username: # 因为没有用户名和密码，所以这两个参数就没有值
    password:
    driver-class-name: org.sqlite.JDBC # sqlite驱动